[package]
name = "asn1rs-macros"
version = "0.2.0"
authors = ["Michael Watzko <michael@watzko.de>"]
edition = "2018"
description = "Macros for asn1rs"
keywords = ["proc", "macro", "asn1", "protobuf", "sql"]
categories = ["parsing"]
repository = "https://github.com/kellerkindt/asn1rs-proc"
license = "MIT/Apache-2.0"
readme = "README.md"


[lib]
proc-macro = true

[features]
default = []
debug-proc-macro = []


[dependencies]
asn1rs-model =  { version = "0.2.0-alpha3", path = "../asn1rs-model" }
syn = {version = "1.0.17", features = ["full"] }
quote = "1.0.3"
